### ISSUE TITLE
Prototype check for UKMO forecasts

### ISSUE THREAD

**Issue by rmctc** [WP-MIP/.github#20]
The Met Office is preparing to provide their WP-MIP contributions.

**Comment by rmctc** [comment]
Email from Duncan:

I have a more practical follow up here on file naming. The convention is for files to be uploaded following this - wpmip_SSS_CCCC_YYYYMMDDHH_MM_II_LL.grib2. 
 
I note the only difference relating to the data fields is the last one (LL). Do I put all the pressure level fields (U, V, Z, q and T) in the one labelled "pl" and all the surface fields in the one called "sl"? What do I label the fixed fields as (LSM and orography)?

**Comment by rmctc** [comment]
The contributions so far have added the orography and LSM to the “single level” (LL=sl) files, then only provided them for the first time step of each run.  A bit of a duplication, but maybe easier than having a separate file for each model just for the two fields.

**Comment by rmctc** [comment]
Email from Duncan:

OK - so put all pressure level data in a single file for each forecast and likewise for all the surface ones too while also including LSM and orography. 

I'll build my processing code towards that. I'll sort some test data but just want to be as close as possible to "correct first time" as I can.

**Comment by duncanackerley** [comment]
Error message I got from grib-check on my local (suggestion to resolve in comment below using grib_set).

FAIL: wpmip_oic_egrr_2024010100_pm_00_pl.grib2
  FAIL: field 1
    FAIL: temperature_pl.wpmip
      FAIL: Basic checks
        FAIL: Wpmip Basic Checks
          FAIL: productionStatusOfProcessedData(255) in [16, 17]
          FAIL: centre(egrr) == 323
          FAIL: subCentre(0) != 0
          FAIL: generatingProcessIdentifier(255) <= 4
          FAIL: dataRepresentationTemplateNumber(0) == 42
          FAIL: bitsPerValue(24) == 16

**Comment by rmctc** [comment]
For your pm files, try something like:

grib_set -r -s bitsPerValue=16,productionStatusOfProcessedData=17,centre=323,subCentre=74, generatingProcessIdentifier=1,dataRepresentationTemplateNumber=42,backgroundProcess=17 in.grib out.grib

For the SIC stream, the generatingProcessIdentifier will need to be changed from 1 to 2.

For the ai and hy models, you'll have to use a different backgroundProcess. We currently don't have those in the [encoding table](https://confluence.ecmwf.int/display/WPMIP/Encoding+details#Encodingdetails-Centrecodesandmodelversions), so let me know once you're ready with those runs we'll have to add new entries.

Note that this command won't be quick because of the repacking required for the bit reduction. Subsequent changes to the metadata should be quicker.

**Comment by duncanackerley** [comment]
Just finished uploading an example pressure level file to UKMO (wpmip_oic_egrr_2024010100_pm_00_pl.grib2). It passes my checks, could you independently verify please? If all is good I'll get on with the rest of the plev upload. Thanks!

**Comment by rmctc** [comment]
All good!  Let me know when the uploads are done and we'll add them to the archive!

**Comment by duncanackerley** [comment]
I'm having serious problems with my single level data. My initial attempt to output to grib2 with IRIS results in several fields being unnamed and lumped together. I've also got similarly awful output from cdo and wgrib2 just refuses to work properly. I can convert from UM output format to netCDF no problem - do you have a suggestion for converting netcdf to grib2? What do you do with your data, @rmctc ? Thanks!

**Comment by rmctc** [comment]
We have a tool that converts our internal file format ("fichier standard") to grib:  I started from the TIGGE example and managed to get it working from there with grib_set.  The ECCODES tools are great for manipulating the file once it's in grib and convert *to* netcdf, but I don't think that they go the other way.  Maybe @innapoli  has some suggestions?

ps. Are the pressure-level files uploads ready?

**Comment by innapoli** [comment]
The only suggestions I have is to try and follow the TIGGE protocol of preparing the data.

**Comment by duncanackerley** [comment]
@innapoli - is there any documentation online for following the TIGGE protocols? I had a look yesterday and I couldn't find anything describing the method. 

@rmctc - our data retrieval system is in terrible health and my initial attempts at retrieving data keep failing (I'm not alone in this problem at the Met Office). I'm starting to have some success today so hopefully I will be able to start uploading imminently...

**Comment by innapoli** [comment]
@duncanackerley. I was more referring to using the same workflow Met Office uses to submit the TIGGE data to ECWMF. I don't know who it is that prepares this from your side, but maybe they can be contacted to see what they do to get the data in the right form before sending to ECMWF? If you want to, I can try and find out who it is.

**Comment by duncanackerley** [comment]
@innapoli - that makes sense. I've found a potential lead and following up on it as we speak. Many thanks for suggesting that idea!

**Comment by duncanackerley** [comment]
@rmctc I have started my upload. I will have January, February and March plev data uploaded within an hour or so. I've checked it at my end and no problems. Let me know if it all looks good from your side. 

@innapoli - I've found the correct person here for TIGGE and got some code to sort things out, so should be fine on that front. Thanks again!

**Comment by rmctc** [comment]
I can see the data out to the end of Sept but nothing after that... has the pl upload stalled?

**Comment by duncanackerley** [comment]
No stalling... just been a bit painful with processing at this end. You should have October, November and December by the time you start this morning. :-)

**Comment by rmctc** [comment]
Transforming the inputs into the archive now ...

**Comment by rmctc** [comment]
Done!

**Comment by duncanackerley** [comment]
Hi Ron. I've uploaded this surface level file - sample_wpmip_oic_egrr_2024010100_pm_00_sl.grib2 - to /incoming/UKMO along with an ouput file (grib_check.out) with the error messages in. I've done everything I can to get it this far (multiple weeks worth of work) and it still isn't right and I've run out of ideas. Lots of things are fine, but there are some issues. If you could have a look and offer any suggestions then that'd be great. The missing field is the total 2D cloud cover. As far as I can see I am setting the grib_messages correctly but the field just refuses to exit the processing step correctly (interesting that the other cloud fields are OK though). 

All thoughts/tips/tricks welcome and I'll give them a go (while remembering I have almost no interaction with GRIB so treat me as a novice... probably explains why I'm struggling).

**Comment by rmctc** [comment]
[Please see instructions in the attached document below, which include this fix]

Got a fix for the 2D cloud cover (tcc).  The level values were bad, so it's just a matter of correcting those, then the parameter gets recognized no problem.  I think it's the "full column" level encoding that was causing your converter problems.  This seems to work:

`grib_set -wshortName=unknown  -stypeOfFirstFixedSurface=1,typeOfSecondFixedSurface=8 sample_wpmip_oic_egrr_2024010100_pm_00_sl.grib2 sample_wpmip_oic_egrr_2024010100_pm_00_sl-withtcc.grib2`

**Comment by rmctc** [comment]
Ok, now there are a few more encoding problems for tcc that we can see because the checker now has some idea of what the field is supposed to be.  There's a time offset of 56min, does that ring a bell?  Then the layer bounds also need to be reset.  It'll be additional args for the grib_set command, but I've got to go get the truck unstuck from the snow ... more later.

**Comment by rmctc** [comment]
[Please see instructions in attached document below, which include this fix]

Ok, had to use the tractor to get the truck out:  solidly stuck ;)

Here's an expanded command that works to get the TCC field (2D clouds) passing all of the checks except for the precision, which is no problem as long as you've confirmed that 5 bits is expected (seems reasonable given the very limited range for the field):

`grib_set -wshortName=unknown  -stypeOfFirstFixedSurface=1,typeOfSecondFixedSurface=8,scaleFactorOfFirstFixedSurface=MISSING,scaledValueOfFirstFixedSurface=MISSING sample_wpmip_oic_egrr_2024010100_pm_00_sl.grib2 sample_wpmip_oic_egrr_2024010100_pm_00_sl-withtcc.grib2`

**Comment by rmctc** [comment]
In all, a set of 6 steps are needed to correct the headers.  I've documented those in the attached file.  These take the initial sample and create a file whose headers pass all of the grib-check requirements except those related to precision, which is fine.  As noted in the attached doc, these changes do not touch the actual data, which is assumed to follow the protocol requests.  Checking with -L and correcting any data errors will be the next step.

Hope this helps!

[wpmip_fix_ukmo_grib.pdf](https://github.com/user-attachments/files/25162769/wpmip_fix_ukmo_grib.pdf)

**Comment by duncanackerley** [comment]
Thank you for the documentation @rmctc! I will get on with following the instructions and do the necessary checks on the data themselves. Many thanks for bringing your tractor out to pull me out of the snow drifts! :-)

**Comment by duncanackerley** [comment]
If I apply your grib_set instructions on the data I produce on the Met Office system then I still get odd errors, if I do it on ECCC then everything is OK (apart from the bits errors). I'll do the 6 steps on ECCC as long as that's OK? If only I'd thought of this straight away it would have saved me 2 days...

**Comment by rmctc** [comment]
Yeah, that's ok.  It's a lot of steps but each one only touches the metadata so they're fairly quick.  Maybe just process the dates serially in your script and clean up the intermediate files between each so that we don't perturb other users and keep the data volume under control.  If you can do this in your personal account on the machine, that would be best ...

**Comment by duncanackerley** [comment]
Yes, will do that. It can do it "on the fly" as I retrieve data from our system (which is going to be slow) and upload to you. It shouldn't impact people.

**Comment by duncanackerley** [comment]
New thing to check - sample_wpmip_oic_egrr_2024010100_pm_00_sl.grib2

It seems fine, but I did notice this error for the accumulated fields: 
FAIL: final_file.grib2
  FAIL: field 795
    FAIL: time_integrated_short_wave_(solar)_radiation_downwards_sfc.wpmip
      FAIL: Basic checks
        FAIL: Range check
          FAIL: value == 0 at step 0

It comes right at the end of checking each of the accumulated fields. I thought the accumulations were supposed to be set to zero at the start of the output, which this error seems to be related to (or not?). Regardless, we are a lot closer (as close as we can get?) to this being correct now.

**Comment by rmctc** [comment]
That's strange:  it was supposed to be fixed in grib-check v0.0.7 (https://github.com/ecmwf/grib-check/issues/15).  Are you running a slightly older version of the checker locally?

**Comment by rmctc** [comment]
I ran the checker on the ECCC server and it looks good:  the only messages are for the nbits, which are expected.  Good to go for the upload!

**Comment by duncanackerley** [comment]
I have a conda environment for the grib-check step... I would have thought that would just update by itself. I'm glad your checks check out and I'll get on with the next phase of the data transfers. HUGE thanks for all of your help again!

**Comment by duncanackerley** [comment]
I'm well on my way with the upload and have some files in ~/incoming/UKMO/slev_tmp. Do you want to check this one looks OK to you? I've just checked it myself and it seems OK: wpmip_oic_egrr_2024010100_pm_00_sl.grib2

**Comment by rmctc** [comment]
Looks good to me: the only messages I see are for the bitsPerValue.  Nice work!

**Comment by duncanackerley** [comment]
Great - thanks! I'll keep on the processing and let you know when it is complete (and tidy up those directories). Have a good weekend!

**Comment by duncanackerley** [comment]
I am in the final stages of finalising the sl data. I will update you later when they are available. 

Other things/updates:
1) I've got head space to consider analyses now. Would the priority be pressure level and mean sea level pressure analyses? Or do you want all data fields (i.e. all the surface level fields) with equal priority? 
2) Marion is investigating whether my attempt at the SIC setup is working. If it is then I will hit "go" on those immediately and upload data as it runs. Keep your fingers and toes crossed. 
3) Once I'm on top of 1 and 2 I can spend a bit more time with Ian Boutle on the hybrid setup, but I wouldn't expect them to be available for the first paper. 
4) I will follow up on our ML runs before Easter. 
5) Please do "prod" me on the above things. Having the occasional reminder brings them back to the front of my mind and is actually really helpful for me so please do check in.

**Comment by duncanackerley** [comment]
The sl data are now ready. They are in /home/swpm001/incoming/UKMO/slev_tmp/complete/

I've got all the data from my pre-processing steps stored in a separate location, which I'll hold on to until you've processed these ones. Once you give me the green light, I'll remove those extra data and put the sl data with the pl data. I'll also clean up any other things in incoming/UKMO.

**Comment by rmctc** [comment]
Great!  I've finished processing the _sl_ data in /home/swpm001/incoming/UKMO/slev_tmp/complete/ .

Green light.

**Comment by rmctc** [comment]
> I am in the final stages of finalising the sl data. I will update you later when they are available.
> 
> Other things/updates:
> 
>     1. I've got head space to consider analyses now. Would the priority be pressure level and mean sea level pressure analyses? Or do you want all data fields (i.e. all the surface level fields) with equal priority?
> 
>     2. Marion is investigating whether my attempt at the SIC setup is working. If it is then I will hit "go" on those immediately and upload data as it runs. Keep your fingers and toes crossed.
> 
>     3. Once I'm on top of 1 and 2 I can spend a bit more time with Ian Boutle on the hybrid setup, but I wouldn't expect them to be available for the first paper.
> 
>     4. I will follow up on our ML runs before Easter.
> 
>     5. Please do "prod" me on the above things. Having the occasional reminder brings them back to the front of my mind and is actually really helpful for me so please do check in.

1. Let's start with pressure-level because is might be easier.  Hopefully the analyzed single-level fields will also be relatively straightforward because there's none of the flux and/or integrated-values complexity.  
2. This is great.  We're also still working on getting the SIC setup underway for ECCC.
3. No worries.  We need to get the paper ready, so we'll go ahead with what we have.  It will be great to have a third hybrid model for the more detailed follow-up evaluations.
4. Excellent.
5. Will do :)

**Comment by duncanackerley** [comment]
I've started the SIC pl data upload for the forecasts I've done. They are stored in incoming/UKMO (and labelled sic). I've done a check and nothing has come up. Could you check independently and verify that please? I'm continuing to upload on the assumption all is OK so the data can be ready as quickly as possible.

**Comment by rmctc** [comment]
Just did a spot check on one of the _pl_ files (I don't see any sic _sl_ files yet), and everything checks out!

**Comment by duncanackerley** [comment]
REALLY pleased to hear that. I haven't got the bandwidth to deal with the sic_sl part yet... next week is the plan. I'm just finishing off the corrected oic_sl files as we speak. Will update later today or tomorrow when they should be done.

**Comment by duncanackerley** [comment]
**I have uploaded all of the pl data for the sic experiments**. I will now get on with processing the sl data - hopefully they'll be there by the end of the week. UPDATE: We have oic data from our ML runs, but the "sic" runs are from ERA5 not ECMWF analyses. I think best to assume we won't provide ml_sic data for now. I will also find out where we are on the hybrid model data.

**Comment by rmctc** [comment]
The _pl_ SIC data are in!

**Comment by duncanackerley** [comment]
Currently multi-tasking while in the meeting :)

The sic data are all there in /incoming/UKMO for sl. I've done a check on the 01-01-2024 file and all seems OK. I'll leave you to have a check and hopefully all looks good to you.

**Comment by rmctc** [comment]
My spot check looked good too... ingesting the files now :)

**Comment by duncanackerley** [comment]
The AI pl oic data have been uploaded to incoming/UKMO. I've done a check and nothing came back, which surprised me as not all the White Paper pressure levels are included. Just for reference in the future, these are the pressure levels provided (as discussed offline). NOTE: these are 10-day forecasts not the 15-days I've provided for the PM sic and oic. 

In hPa: 1000, 925, 850, 700, 500, 400, 300, 250, 200, 150, 100, 50

Let me know when you've done your checks and I'll adjust anything you notice. I'm on to the sl data as we speak.

**Comment by rmctc** [comment]
The grib-check tool only tries to confirm the validity of the fields that **are** provided, so it doesn't report on missing fields.  It also reports if it finds fields that it doesn't expect.

I'll get on top of those AI _pl_ files right away ...

**Comment by duncanackerley** [comment]
Interesting... I thought it shouted out if something was missing from the WP-MIP setup. Good to know it doesn't do that.

**Comment by duncanackerley** [comment]
I'm getting this error on the ECCC server, which I don't get with running grib_check at the Met Office. 

FAIL: final2_wpmip_oic_egrr_2024112300_ai_00_sl_tmp.grib2
  FAIL: field 1
    FAIL: mean_sea_level_pressure_sfc.wpmip
      FAIL: Basic checks
        FAIL: Wpmip Basic Checks
          FAIL: centre(323) == wpmip

There seems to be an issue with wpmip - even though I set the -C wpmip option. Have I missed something? The files seem absolutely fine apart from this.

**Comment by rmctc** [comment]
Ah, I installed the v0.0.8 of grib-check yesterday after Richard's announcement.  I wonder if it's got a problem.

Are you using v0.0.7 at the Met Office?

**Comment by duncanackerley** [comment]
I have a conda environment that I set up in November 2025 so I'm guessing it probably is 0.0.7. Are you happy for me to finalise the files (and assume this is a bug) or should I hang fire?

**Comment by rmctc** [comment]
I'm seeing another set of warnings out of the sl file.  Are you not getting this one either?

<img width="734" height="166" alt="Image" src="https://github.com/user-attachments/assets/90c3cb20-f754-4f3d-93af-b012eb250d70" />

**Comment by duncanackerley** [comment]
Those aren't my final files. I need to run one more processing script on them before they are ready.  This one is a "ready" file - final_wpmip_oic_egrr_2024010100_ai_00_sl_tmp.grib2 

(in the directory  ~/incoming/UKMO/new_sl_data)

I rename the files to be correct after that extra step too.

**Comment by rmctc** [comment]
Got it!  That one looks good.

I've just downgraded grib-check to v0.0.7 and am getting no more warnings.  I'll file a bug report on the grib-check project and we'll upgrade once it's fixed.

**Comment by rmctc** [comment]
https://github.com/ecmwf/grib-check/issues/24

**Comment by duncanackerley** [comment]
Fabulous! I'll hit go on the final processing step and update you when everything is ready.

**Comment by duncanackerley** [comment]
The AI SL fields produced by our ML model (a subset of the full list) are now ready and checked. Happy for you to double check and process if all OK.

**Comment by janhueychen** [comment]
Hi, Please let me know if I missed. I haven't seen the UKMO OIC/AI surface data posted. Could someone let me know if the surface data is on its way?  https://hpfx.collab.science.gc.ca/~swpm001/WP-MIP/forecasts/oic/egrr/ai_00/

**Comment by rmctc** [comment]
It looks like the data are in incoming/UKMO (core protocol only).  I'll start ingesting them now:  thanks for the heads-up @janhueychen

**Comment by janhueychen** [comment]
@rmctc Thanks Ron!

**Comment by rmctc** [comment]
Done:  the UKMO OIC AI single-level data are posted.

**Comment by duncanackerley** [comment]
Thanks @rmctc! I've only just started looking at the data download so hadn't noticed. Thanks again.

**Comment by rmctc** [comment]
@duncanackerley , did you see Masashi's note at https://github.com/WP-MIP/.github/issues/39#issuecomment-4460955846?  This may be a wgrib thing rather than a problem with the data, but a double-check would be great.

**Comment by rmctc** [comment]
I just ran `grib-check -Cwpmip -L -f wpmip_oic_egrr_2024122900_pm_00_sl.grib2` and don't see any sign of a problem.  Of course the fact that the values are well within the expected range means that the "-L" won't catch anything.  But at least this means that the headers are as-expected.

**Comment by duncanackerley** [comment]
On it @rmctc

**Comment by duncanackerley** [comment]
OK, so my data at the Met Office are fine; however, I am seeing the problem Masashi has mentioned in the downloaded data. Something is happening to the data when converting from grib2 that I make here into the grib2 I put on the web site. I'll check the February data and the SIC data too for further checks. Ultimately, we have the correct data from the model and something odd has happened in the conversion.

**Comment by rmctc** [comment]
Ah, the data in incoming/UKMO were updated on 19 March, but the archive was last updated on 4 March.  So the files with the correct msl aren't the ones that were used to generate what you can download.

Going back through this issue, I see that we were working on the SIC inputs in mid-March, but no mention of an update to the OIC data.  Looking at the incoming/UKMO directory, I think it's just the OIC pm _sl_ files that were uploaded on 19 March, with the _pl_ files still being those that arrived on 2 Dec.

From the thread, it looks like there were quite a few manipulations on the _sl_ files in early March (i.e. the ones that were used to create what is currently in the archive), so maybe these 19 March uploads were meant to be a clean start?

**Comment by rmctc** [comment]
Given that updating the existing data in the archive isn't something we want to do anymore, I think that we're best-off ingesting these as a new "v01" dataset from the Met Office for the physical model.  Does that sound ok to you, Duncan?

**Comment by janhueychen** [comment]
Hi, Does that mean the MSLP in the current forecasts/oic/egrr/pm_00 is incorrect?

**Comment by duncanackerley** [comment]
OK... I think I can see more to this now. The newer data from 19th March were related to this issue #38 where we noted the precipitation was odd. I think that you only replaced the precipitation data in the archive @rmctc and maybe it was worth replacing the whole thing(?). The correction was applied to all data in the files if I remember correctly so I'd be willing to trust what's in there for 19th March entries. Equally, I can re-upload or just move the data to another location on the server that's easier to pick up. 

@janhueychen - yes, I think that means they are incorrect at the moment.

**Comment by rmctc** [comment]
@duncanackerley , I've prepared the new data as "v01" to avoid overwriting the existing dataset.  We can note that users should move to the new data, particularly if they're looking at single-level fields.  If they've already done an analysis using the pressure-level data, those results remain valid.  For now the data are in a temporary staging area:  are you ok with me publishing it in the archive as a new version?

**Comment by duncanackerley** [comment]
Yes, absolutely fine if that's the easier route. I assume there is no other issue (beyond technicalities) in having a "v01"? Is it worth letting me download a test before letting other know? I'm primed ready to check.

**Comment by duncanackerley** [comment]
Just to say as well - the SIC data test I downloaded looked absolutely fine.

**Comment by janhueychen** [comment]
Thanks @duncanackerley @rmctc 
Just want to confirm that this issue only affect the UKMO OIC/physical or all models (OIC/AI, SIC/physical) are affected? I need to retrieve the tracker outputs using the wrong surface data (MSLP).

**Comment by janhueychen** [comment]
> Just to say as well - the SIC data test I downloaded looked absolutely fine.

Thanks! Just saw this message. So, only the two OIC models are affected?

**Comment by duncanackerley** [comment]
Just OIC physical is problematical as far as I know, OIC AI should be fine.

**Comment by rmctc** [comment]
> Yes, absolutely fine if that's the easier route. I assume there is no other issue (beyond technicalities) in having a "v01"? Is it worth letting me download a test before letting other know? I'm primed ready to check.

Good idea.  You can access the data directly at https://hpfx.collab.science.gc.ca/~swpm001/WP-MIP/forecasts/oic/egrr/pm_01/

Once you give me the thumbs-up, I'll redo the indexing so that it will appear on the portal.

**Comment by duncanackerley** [comment]
I've tested the January data and get ranges of ~935 hPa to ~1047 hPa for one forecast and ~927 hPa to ~1058 hPa. I think we're good. Would you like me to check some other random fields or should we accept this? Results of my test in IRIS/python below for confirmation. 

Forecast initialised on 1st Jan 2024
>>> print(data.data[:,:,:].max())
104778.2734375
>>> print(data.data[:,:,:].min())
93564.8046875
Forecast initialised on 1st Jan 2024
>>> print(data2.data[:,:,:].max())
105809.9140625
>>> print(data2.data[:,:,:].min())
92798.5546875

**Comment by rmctc** [comment]
I just checked the 2-m temperature the range there looks ok too.  I think we're good to go.  I'll run the indexing.

**Comment by duncanackerley** [comment]
Awesome - thanks Ron! Time zones are no barrier. 😁

**Comment by duncanackerley** [comment]
I've finally got some space to complete the processing of the hybrid model data from the Met Office. Shall I use the same method for uploading as above?

**Comment by rmctc** [comment]
Yup:  the cleanup is done so we should have enough space for the new data.  Let'r rip!

**Comment by duncanackerley** [comment]
I've uploaded the 3D data for the hybrid model. You can find them in /incoming/UKMO/hybrid. I've run the grib checker but I've been having problems with it completing. I _think_ everything is OK but an extra check would be good. The single level data might be a little while as I've got some problems with processing the data. I am on it though.

**Comment by rmctc** [comment]
Excellent!  I've ingested and _pl_ data and confirmed that it's available to download.  I'll keep the issue closed for now and we'll reopen when the _sl_ files are ready.

**Comment by janhueychen** [comment]
@duncanackerley Hi Duncan, Would UKMO provide surface data for its hy_00?

**Comment by duncanackerley** [comment]
@janhueychen - we will do. Had a computational infrastructure overhaul and only just able to start retrieving these data from our archive space now. I will update ASAP.
